export const UPDATE_COORDINATES = "UPDATE_COORDINATES"
export const COORDINATES_LOADED = "COORDINATES_LOADED"
export const CREW_LOADED = "CREW_LOADED"
export const UPDATE_CREW = "UPDATE_CREW"
export const UPDATE_DATE = "UPDATE_DATE"

export const API_GET_COORDINATES_ERRORED = "API_GET_COORDINATES_ERRORED"
export const API_GET_CREW_ERRORED = "API_GET_CREW_ERRORED"